### ISSUE TITLE
大佬给看看咋回事？好像还是不兼容androidx

### ISSUE THREAD

**Issue by lexluthors** [weikaiyun/Arouter#1]
大佬你这个需要配置帐号密码才能拉取吗？能不能放到jitpack？

**Comment by lexluthors** [comment]
@weikaiyun 是我导错包了，没有错误。就是不能匿名下载。要是发布到jitpack就好了。

**Comment by weikaiyun** [comment]
匿名下载，github已经在规划中，可能年底会支持，不过目前使用只读的pat也还好。jitpack暂时没看到可以发布插件。

**Comment by weikaiyun** [comment]
匿名下载，GithubPackages可能年底就会支持，暂时使用只读的pat下载也还好，只是添加一个maven仓库而已。
